#include <sys/syscall.h>
#include <unistd.h>

const char j0hnniewa1ker[] =	
"# docker run --rm j0hnniewa1ker/readme > README.md                              \n"
"```                                                                             \n"
"        _  ___  _                 _                    _ _                      \n"
"       (_)/ _ \\| |__  _ __  _ __ (_) _____      ____ _/ | | _____ _ __         \n"
"       | | | | | '_ \\| '_ \\| '_ \\| |/ _ \\ \\ /\\ / / _` | | |/ / _ \\ '__|  \n"
"       | | |_| | | | | | | | | | | |  __/\\ V  V / (_| | |   <  __/ |           \n"
"      _/ |\\___/|_| |_|_| |_|_| |_|_|\\___| \\_/\\_/ \\__,_|_|_|\\_\\___|_|     \n"
"     |__/                                                                       \n"
"```                                                                             \n"
"## Summary                                                                      \n"
"- A self-starter who needs little direction but welcomes collaboration          \n"
"- I most enjoy deciphering the inner workings of legacy and forgotten systems   \n"
"  - documenting what I discover into issues to track with the team              \n"
"  - stratagizing with stakeholders, planning what to modernize next             \n"
"## Experience                                                                   \n"
"### IBM                                                 June 2021 - October 2023\n"
"Client Engineering Technology Engineer                                          \n"
"- Mentored clients and colleagues great practices around learning new skills    \n"
"- Created content for learning Cloud Native approaches                          \n"
"--------------------------------------------------------------------------------\n"
"### Starbucks                                          September 2016 - May 2021\n"
"Application Developer                                                           \n"
"- Lead Performance Test team                                                    \n"
"  - pushed for code to be converted to .Net core                                \n"
"  - deployed 20,000 docker containers daily to test IoT Hub application         \n"
"--------------------------------------------------------------------------------\n"
"### Efinancial                                    November 2014 - September 2016\n"
"Devops Engineer                                                                 \n"
"- Built dev, test and pre-producion environments in AWS via PowerShell          \n"
"- Upgraded TFS Server and mentored team how to use Release Manager              \n"
"--------------------------------------------------------------------------------\n"
"### Adobe (contact)                                     June 2013 - October 2014\n"
"Release Engineer                                                                \n"
"- Migrated legacy build systems to Jenkins and mentored teams how to manage them\n"
"- Developed WinPE to automate Windows deployments as VMs or on bare metal       \n"
"--------------------------------------------------------------------------------\n"
"### Microsoft (contract)                               February 2013 - June 2013\n"
"Build Engineer                                                                  \n"
"- Responsible for build automation, scripting, and release implementation       \n"
"- Validated deployments passed QA before releasing to Pre-Production|Production \n"
"--------------------------------------------------------------------------------\n"
"```                                                                             \n"
"gcc -o readme --static -g readme.c                                              \n"
"docker build . -t j0hnniewa1ker/readme                                          \n"
"docker push j0hnniewa1ker/readme                                                \n"
"git add README.md readme.c Dockerfile                                                      \n"
"git commit -m \"complicated README.md update process\"                          \n"
"git push                                                                        \n"
"```                                                                             \n"
"## A1                                                                           \n"
"- Makefile                                                                      \n"
"- GitBucket, Gitea or GitLab?                                                   \n"
"- Jenkins or Drone for Continuous Integration                                   \n"
"\n";
int main() {
  syscall(SYS_write, STDOUT_FILENO, j0hnniewa1ker, sizeof(j0hnniewa1ker) - 1);
  return 0;
}
