#include <sys/syscall.h>
#include <unistd.h>

const char j0hnniewa1ker[] =	
"# docker run --rm j0hnniewa1ker/readme:rpgle > README.md                        \n"
"```                                                                             \n"
"        _  ___  _                 _                    _ _                      \n"
"       (_)/ _ \\| |__  _ __  _ __ (_) _____      ____ _/ | | _____ _ __         \n"
"       | | | | | '_ \\| '_ \\| '_ \\| |/ _ \\ \\ /\\ / / _` | | |/ / _ \\ '__|  \n"
"       | | |_| | | | | | | | | | | |  __/\\ V  V / (_| | |   <  __/ |           \n"
"      _/ |\\___/|_| |_|_| |_|_| |_|_|\\___| \\_/\\_/ \\__,_|_|_|\\_\\___|_|     \n"
"     |__/                                                                       \n"
"```                                                                             \n"
"## Summary                                                                      \n"
"- I most enjoy deciphering the inner workings of legacy and forgotten systems   \n"
"  - documenting what I discover into issues to track with the team              \n"
"  - strategizing with stakeholders, planning what to modernize next             \n"
"-  Broad Experience                                                             \n"
"  - Started my Career in building PCs, quickly promoted to Network Engineer     \n"
"  - Novell Consultant helping clients with Netware, Zenworks, GroupWise         \n"
"  - Systems Engineer at Microsoft configuring routers, switches, servers        \n"
"  - Test Engineer at Microsoft focusing on deployment and performance testing   \n"
"  - Release Engineer at Adobe migrating legacy build systems to jenkins         \n"
"  - Application Developer at Starbucks                                          \n"
"  - Technology Engineer at IBM designing MVPs with clients                      \n"
"    - Container workshops                                                       \n"
"    - Openshift workshops                                                       \n"
"    - Ansible wokshops                                                          \n"
"    - Restricted System demos on z15 implementing OpenShift solutions           \n"
"    - z/OS pipeline demos                                                       \n"
"    - Experience installing Mirrored SQL Servers, Log Shipping, Data Warehouses \n"
"      - Tracking down, resolving replication issues                             \n"
"      - Writing automation including SQL queries                                \n"
"        - validate system restores                                              \n"
"        - migration of DBs to new hosts                                         \n"
"        - performance testing                                                   \n"
"- committed to coursework and becoming solidly proficient within 12 months.     \n"
"  - RPGLE                                                                       \n"
"  - RPG/400                                                                     \n"
"  - CL                                                                          \n"
"## Experience                                                                   \n"
"### IBM                                                 June 2021 - October 2023\n"
"Client Engineering Technology Engineer                                          \n"
"- Mentored clients and colleagues great practices around learning new skills    \n"
"- Created content for learning Cloud Native approaches                          \n"
"--------------------------------------------------------------------------------\n"
"### Starbucks                                          September 2016 - May 2021\n"
"Application Developer                                                           \n"
"- Nginx Project built with Chef Automate including Kitchen and Inspec validation\n"
"- Virtualized Windows 10 IoT solution delivered with Marimba                    \n"
"- OpenStack project focused on improving image delivery to edge devices         \n"
"- Packer qemu_builder project to manage changes to VM images                    \n"
"- Lead Performance Test team                                                    \n"
"  - pushed for code to be converted to .Net core                                \n"
"  - deployed 20,000 docker containers daily to test IoT Hub application         \n"
"--------------------------------------------------------------------------------\n"
"### Efinancial                                    November 2014 - September 2016\n"
"Devops Engineer                                                                 \n"
"- Built dev, test and pre-producion environments in AWS via PowerShell          \n"
"- Upgraded TFS Server and mentored team how to use Release Manager              \n"
"--------------------------------------------------------------------------------\n"
"### Adobe (contact)                                     June 2013 - October 2014\n"
"Release Engineer                                                                \n"
"- Migrated legacy build systems to Jenkins and mentored teams how to manage them\n"
"- Developed WinPE to automate Windows deployments as VMs or on bare metal       \n"
"--------------------------------------------------------------------------------\n"
"### Microsoft (contract)                               February 2013 - June 2013\n"
"Build Engineer                                                                  \n"
"- Responsible for build automation, scripting, and release implementation       \n"
"- Validated deployments passed QA before releasing to Pre-Production|Production \n"
"--------------------------------------------------------------------------------\n"
"```                                                                             \n"
"gcc -o readme --static -g readme.c                                              \n"
"docker build . -t j0hnniewa1ker/readme:rpgle                                    \n"
"docker push j0hnniewa1ker/readme:rpgle                                          \n"
"git add README.md readme.c                                                      \n"
"git commit -m \"Programmer Analyst at Great Plains Manufacturing\"              \n"
"git push                                                                        \n"
"```                                                                             \n"
"## [A1](https://github.com/5eed1ab/A1)                                          \n"
"- Makefile                                                                      \n"
"- [GitBucket||Gitea||GitLab?](https://github.com/J0hnnieWa1ker/.github/issues/1)\n"
"- Jenkins or Drone for Continuous Integration                                   \n"
"\n";
int main() {
  syscall(SYS_write, STDOUT_FILENO, j0hnniewa1ker, sizeof(j0hnniewa1ker) - 1);
  return 0;
}
